# Generated by Django 6.0.1 on 2026-01-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('bidding', 'Bidding'), ('active', 'Active'), ('completed', 'Completed')], default='bidding', max_length=20),
        ),
    ]
