# Generated by Django 6.0.1 on 2026-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_task_task_shot_remove_task_status_shot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pipeline_step',
            field=models.CharField(choices=[('modeling', 'Modeling'), ('texturing', 'Texturing'), ('rigging', 'Rigging'), ('animation', 'Animation'), ('lighting', 'Lighting'), ('compositing', 'Compositing')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
