# Generated by Django 6.0.1 on 2026-01-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_pipeline_step_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pipeline_step',
            field=models.CharField(choices=[('modeling', 'Modeling'), ('texturing', 'Texturing'), ('rigging', 'Rigging'), ('animation', 'Animation'), ('lighting', 'Lighting'), ('compositing', 'Compositing')], default='modeling', max_length=20),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file_path', models.FileField(upload_to='versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.shot')),
            ],
        ),
    ]
