# Generated by Django 6.0.1 on 2026-01-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_pipeline_step_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['shot', '-version_number']},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('shot', 'version_number')},
        ),
    ]
