# Generated by Django 6.0.1 on 2026-01-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_version_options_alter_version_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
