# Generated by Django 6.0.1 on 2026-01-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected')], default='needs_review', max_length=20),
        ),
    ]
