# Generated by Django 6.0.1 on 2026-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_version_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
