# Generated by Django 6.0.1 on 2026-01-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('needs_changes', 'Needs Changes'), ('needs_review', 'Needs Review'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='needs_review', max_length=20),
        ),
    ]
