# Generated by Django 6.0.1 on 2026-01-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('on_hold', 'On Hold')], default='not_started', max_length=20),
        ),
    ]
